name: Trigger auto deployment for appspace244545

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/appspace244545-AutoDeployTrigger-0279d022-efed-4fe0-b01c-069b57041604.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPSPACE244545_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPSPACE244545_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPSPACE244545_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryb6v72qek6ssog.azurecr.io
          registryUsername: ${{ secrets.APPSPACE244545_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPSPACE244545_REGISTRY_PASSWORD }}
          containerAppName: appspace244545
          resourceGroup: next13onswab10b
          imageToBuild: containerregistryb6v72qek6ssog.azurecr.io/appspace244545:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


