name: Trigger auto deployment for container1230494

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container1230494-AutoDeployTrigger-914c85f2-1227-4c7d-9be2-a403b2e8dc2c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINER1230494_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINER1230494_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINER1230494_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryvoj5arwja3y5y.azurecr.io
          registryUsername: ${{ secrets.CONTAINER1230494_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINER1230494_REGISTRY_PASSWORD }}
          containerAppName: container1230494
          resourceGroup: jamstack1ba97
          imageToBuild: containerregistryvoj5arwja3y5y.azurecr.io/container1230494:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


