name: Trigger auto deployment for container-app-b6v72qek6ssog

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/src/**'
    - '.github/workflows/container-app-b6v72qek6ssog-AutoDeployTrigger-acbc3f77-1f1a-42d2-85fe-8b0bba54a0fa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPB6V72QEK6SSOG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPB6V72QEK6SSOG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPB6V72QEK6SSOG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: containerregistryb6v72qek6ssog.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPB6V72QEK6SSOG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPB6V72QEK6SSOG_REGISTRY_PASSWORD }}
          containerAppName: container-app-b6v72qek6ssog
          resourceGroup: next13onswab10b
          imageToBuild: containerregistryb6v72qek6ssog.azurecr.io/container-app-b6v72qek6ssog:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


