# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - site4

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_28E0AC55F54749EEAD219CC2985B6B0A }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_359F80306F404AAA9C50B033892D9BE0 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_28E0AC55F54749EEAD219CC2985B6B0A }}/linux:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69FB571C91EC4DCBA5F19D515BAFD499 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5298D3B8E234B5E8E05F4D2976150E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0BF4B352E7D45238088B0EE959D234B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'site4'
          slot-name: 'Production'
          images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_28E0AC55F54749EEAD219CC2985B6B0A }}/linux:${{ github.sha }}'
          