# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gha-test-dockerhub-linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://stpelleg09.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_92a08b980b2444689066ee653ec7c4f0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7bbdce89443c4beba92c1e876089c26c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: stpelleg09.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92a08b980b2444689066ee653ec7c4f0 }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gha-test-dockerhub-linux'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a1e895814fcc4e5c980b9fc98d1b86af }}
        images: 'stpelleg09.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92a08b980b2444689066ee653ec7c4f0 }}/hello-world:${{ github.sha }}'