# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - site10(Production), Build and deploy container app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D0FE9E6E177D46DBB046A2D0B883C1C8 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_AAB650729599462BB141B85B45922CBF }}

    - run: |
        docker build . -t index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D0FE9E6E177D46DBB046A2D0B883C1C8 }}/linux:${{ github.sha }}
        docker push index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D0FE9E6E177D46DBB046A2D0B883C1C8 }}/linux:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: site10
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8220B7D7B1C94198AC5C06F9C9C2062C }}
        images: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D0FE9E6E177D46DBB046A2D0B883C1C8 }}/linux:${{ github.sha }}

