name: Trigger auto deployment for myapp2-eastus2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myapp2-eastus2-AutoDeployTrigger-d02dc92d-9ee9-4486-82ec-18ea3fdc09f1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYAPP2EASTUS2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYAPP2EASTUS2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYAPP2EASTUS2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: stpellegtestregistry.azurecr.io
          registryUsername: ${{ secrets.MYAPP2EASTUS2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYAPP2EASTUS2_REGISTRY_PASSWORD }}
          containerAppName: myapp2-eastus2
          resourceGroup: containerapp
          imageToBuild: stpellegtestregistry.azurecr.io/myapp2-eastus2:${{ github.sha }}
          


