name: Trigger auto deployment for space9ik4562

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/space9ik4562-AutoDeployTrigger-7d32c5b6-d127-4db0-ad91-283defd7e06d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPACE9IK4562_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPACE9IK4562_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPACE9IK4562_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryb6v72qek6ssog.azurecr.io
          registryUsername: ${{ secrets.SPACE9IK4562_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPACE9IK4562_REGISTRY_PASSWORD }}
          containerAppName: space9ik4562
          resourceGroup: next13onswab10b
          imageToBuild: containerregistryb6v72qek6ssog.azurecr.io/space9ik4562:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


