name: Trigger auto deployment for stpelleg-ca-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/stpelleg-ca-1-AutoDeployTrigger-966bdbdf-bfb3-42c0-9b5f-f0a986038fff.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: stpelleg09.azurecr.io
          username: ${{ secrets.STPELLEGCA1_REGISTRY_USERNAME }}
          password: ${{ secrets.STPELLEGCA1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stpelleg09.azurecr.io/stpelleg-ca-1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STPELLEGCA1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n stpelleg-ca-1 -g containerapps-rg --server stpelleg09.azurecr.io --username  ${{ secrets.STPELLEGCA1_REGISTRY_USERNAME }} --password ${{ secrets.STPELLEGCA1_REGISTRY_PASSWORD }}
            az containerapp update -n stpelleg-ca-1 -g containerapps-rg --image stpelleg09.azurecr.io/stpelleg-ca-1:${{ github.sha }}
